
-- v1 is $USER
-- v2 is '$USER_PWD'

REVOKE ALL PRIVILEGES ON SCHEMA public FROM :v1;

REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM :v1;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA information_schema FROM :v1;
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA pg_catalog FROM :v1;

REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM :v1;

DROP USER :v1;

